version: '2'
services:
    jhipsterhttpsession-app:
        image: jhipsterhttpsession
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterhttpsession-mysql:3306/jhipsterhttpsession?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterhttpsession-mysql:
        extends:
            file: mysql.yml
            service: jhipsterhttpsession-mysql
